language: objective-c
osx_image: xcode9.2

env:
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
    - gem install cocoapods
    - gem install xcpretty -N
    - brew update
    - brew install swiftlint || true
script:
    - set -o pipefail
    - xcodebuild -workspace PivxWallet.xcworkspace -scheme pivxwallet -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.1' ONLY_ACTIVE_ARCH=NO
    - swiftlint
