language: objective-c
osx_image: xcode9.2

env:
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
    - gem install cocoapods
    - gem install xcpretty -N
    - brew update
    - brew install swiftlint || true
script:
    - set -o pipefail
    - xcodebuild -project PivxWallet.xcodeproj -scheme pivxwallet -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    - swiftlint
